import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { FunctionDeclarationSchemaType } from "@google-cloud/vertexai";
import type { Tool, Part } from "@google-cloud/vertexai";
import { getModel } from "@/lib/gemini";
import { getWaitTime } from "@/lib/timeline";
import venueConfig from "../../../../venues/chinnaswamy.json";
import type { Station } from "@/types/venue";

const MATCH_DURATION = 210;

const MessageSchema = z.object({
  role: z.enum(["user", "model"]),
  content: z.string().min(1).max(2000),
});

const ChatRequestSchema = z.object({
  messages: z.array(MessageSchema).min(1).max(20),
  matchStartedAt: z.number().int().positive(),
  seat: z.object({ section: z.string(), row: z.string(), number: z.string() }),
  preferences: z.object({ dietary: z.array(z.string()), avoidCrowds: z.boolean() }),
});

function computeElapsed(matchStartedAt: number): number {
  return Math.max(0, Math.min(MATCH_DURATION, (Date.now() - matchStartedAt) / 60_000));
}

function matchPhase(elapsed: number): string {
  if (elapsed < 95) {
    const over = Math.min(20, Math.floor((elapsed / 95) * 20));
    return `1st innings, over ${over}/20`;
  }
  if (elapsed < 115) return "innings break";
  const over = Math.min(20, Math.floor(((elapsed - 115) / 95) * 20));
  return `2nd innings, over ${over}/20`;
}

function getVenueState(elapsed: number, category?: string) {
  const stations = venueConfig.stations as Station[];
  return stations
    .filter((s) => !category || s.category === category)
    .map((s) => ({
      id: s.id,
      name: s.name,
      category: s.category,
      sections: s.sections,
      waitMinutes: Math.round(getWaitTime(s.id, elapsed) * 10) / 10,
      forecastIn10min: Math.round(getWaitTime(s.id, Math.min(MATCH_DURATION, elapsed + 10)) * 10) / 10,
    }))
    .sort((a, b) => a.waitMinutes - b.waitMinutes);
}

const TOOLS: Tool[] = [
  {
    functionDeclarations: [
      {
        name: "get_venue_state",
        description:
          "Returns current and 10-minute forecast wait times (in minutes) for all venue stations. Call this before answering any question about queues, food, restrooms, or crowd levels.",
        parameters: {
          type: FunctionDeclarationSchemaType.OBJECT,
          properties: {
            category: {
              type: FunctionDeclarationSchemaType.STRING,
              description: "Filter by station type. Omit to return all.",
              enum: ["concession", "restroom", "gate"],
            },
          },
        },
      },
    ],
  },
];

export async function POST(req: NextRequest) {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "invalid json" }, { status: 400 });
  }

  const parsed = ChatRequestSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.flatten() }, { status: 422 });
  }

  const { messages, matchStartedAt, seat, preferences } = parsed.data;
  const elapsed = computeElapsed(matchStartedAt);

  const systemInstruction = `You are StadiumPal, an AI concierge for M. Chinnaswamy Stadium, Bangalore.
Current match: IPL T20, ${matchPhase(elapsed)}.
User seat: Section ${seat.section}, Row ${seat.row}, Seat ${seat.number}.
Dietary: ${preferences.dietary.join(", ") || "none stated"}.
${preferences.avoidCrowds ? "User prefers quieter areas with shorter queues." : ""}

Always call get_venue_state before answering questions about wait times, food, or restrooms.
Responses must be short and actionable — this is a mobile app. 2–3 sentences max. No markdown headers or bullet points.`;

  const model = getModel();

  // Skip the client-side greeting (index 0, role: "model") — it wasn't generated by
  // the API and would break the expected user-first history pattern.
  const history = messages.slice(1, -1).map((m) => ({
    role: m.role,
    parts: [{ text: m.content }] as Part[],
  }));

  const lastMsg = messages[messages.length - 1];

  try {
    const chat = model.startChat({
      systemInstruction: { role: "system", parts: [{ text: systemInstruction }] },
      tools: TOOLS,
      history,
    });

    let result = await chat.sendMessage([{ text: lastMsg.content }]);
    let response = result.response;

    // Resolve tool calls — Gemini may call get_venue_state before answering
    for (let round = 0; round < 3; round++) {
      const parts = response.candidates?.[0]?.content?.parts ?? [];
      const fnPart = parts.find((p) => "functionCall" in p && p.functionCall);
      if (!fnPart || !("functionCall" in fnPart) || !fnPart.functionCall) break;

      const { name, args } = fnPart.functionCall;
      let fnResult: unknown;

      if (name === "get_venue_state") {
        const category = (args as Record<string, string>)?.category;
        fnResult = getVenueState(elapsed, category);
      } else {
        fnResult = { error: "unknown function" };
      }

      result = await chat.sendMessage([
        { functionResponse: { name, response: { result: fnResult } } } as Part,
      ]);
      response = result.response;
    }

    const text =
      response.candidates?.[0]?.content?.parts?.find((p) => "text" in p && p.text)?.text ??
      "Sorry, I couldn't get a response right now. Try again in a moment.";

    return NextResponse.json({ message: text as string });
  } catch (err) {
    console.error("chat error", err);
    return NextResponse.json({ error: "service unavailable" }, { status: 503 });
  }
}
